# Generated by Django 3.1.5 on 2021-02-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210217_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_no',
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=30),
        ),
    ]
