# Generated by Django 3.1.5 on 2021-02-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_auction',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
