# Generated by Django 3.1.5 on 2021-02-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210222_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
