# Generated by Django 3.1.5 on 2021-02-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210223_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_files/'),
        ),
    ]
