# Generated by Django 3.1.5 on 2021-02-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
