# Generated by Django 3.1.5 on 2021-02-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20210224_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='second_name',
        ),
    ]
