# Generated by Django 3.1.5 on 2021-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_auto_20210224_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='Anonymous User', max_length=24),
        ),
    ]
